name: flutter_system_manager
description: A Windows-first Flutter desktop portfolio project for safe system inspection.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  http: ^1.6.0

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
